"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-20 20:18:19.888585
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('provincia', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('cuit', sa.String(length=13), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuit'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('emergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('nivel_gravedad', sa.Enum('BAJO', 'MEDIO', 'ALTO', 'CRITICO', name='gravedad', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('zona_afectada', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('REGISTRADA', 'CONVOCATORIA', 'CERRADA', name='estadoemergencia', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('bonita_case_id', sa.Integer(), nullable=True),
    sa.Column('ventana_ofertas_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bonita_case_id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.Enum('MUNICIPIO', 'COORDINADOR', 'ONG', 'AUDITOR', name='rol', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('ong_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.ForeignKeyConstraint(['ong_id'], ['ong.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('lote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergencia_id', sa.Integer(), nullable=False),
    sa.Column('recurso', sa.String(length=120), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['emergencia_id'], ['emergencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oferta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergencia_id', sa.Integer(), nullable=False),
    sa.Column('ong_id', sa.Integer(), nullable=False),
    sa.Column('version_actual', sa.Integer(), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['emergencia_id'], ['emergencia.id'], ),
    sa.ForeignKeyConstraint(['ong_id'], ['ong.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emergencia_id', 'ong_id')
    )
    op.create_table('oferta_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('recurso', sa.String(length=120), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ),
    sa.ForeignKeyConstraint(['oferta_id'], ['oferta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oferta_item')
    op.drop_table('oferta')
    op.drop_table('lote')
    op.drop_table('usuario')
    op.drop_table('emergencia')
    op.drop_table('ong')
    op.drop_table('municipio')
    # ### end Alembic commands ###
